version: "3.9"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    #    labels:
    #      - "name=redis"
    #      - "mode=standalone"
    environment:
      TZ: Asia/Seoul
#    command: redis-server /usr/local/conf/redis.conf

networks:
  default:
    name: redis-example-network
    external: true
